version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5432:5432"  # Cambiado a "5432:5432" para mapear el puerto correctamente
    volumes:
      - ./postgres:/var/lib/postgresql/data  # Espacio agregado después del guión "-"
